[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyABS"
authors = [{name = "xiaoyu,zhang", email = "always.zhang@gmail.com"}]
dynamic = ["version", "description"]
